import Head from "next/head";

import SignUpEnabled from "~/components/landing/sign-up-enabled";
// import SignUpDisabled from "~/components/landing/sign-up-disabled";

export default function Landing() {
  return (
    <>
      <Head>
        <title>Furshare by MrDemonWolf</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignUpEnabled />
    </>
  );
}
